$enc = [System.Text.Encoding]::GetEncoding(936)

$lines = @(
    '@echo off',
    'chcp 65001 >nul',
    'setlocal enabledelayedexpansion',
    '',
    'echo ========================================',
    'echo   ZhiXueBan - One-Click Start',
    'echo ========================================',
    'echo.',
    '',
    ':: Get project root (script is in scripts\start\, go up two levels)',
    'pushd "%~dp0\..\.."',
    'set "PROJECT_ROOT=%CD%"',
    'popd',
    'set "BACKEND_DIR=%PROJECT_ROOT%\backend"',
    'set "FRONTEND_DIR=%PROJECT_ROOT%\frontend"',
    '',
    'echo Project root : %PROJECT_ROOT%',
    'echo Backend dir  : %BACKEND_DIR%',
    'echo Frontend dir : %FRONTEND_DIR%',
    'echo.',
    '',
    ':: Check directories',
    'if not exist "%BACKEND_DIR%" (',
    '    echo [FAIL] Backend dir not found: %BACKEND_DIR%',
    '    pause',
    '    exit /b 1',
    ')',
    'if not exist "%FRONTEND_DIR%" (',
    '    echo [FAIL] Frontend dir not found: %FRONTEND_DIR%',
    '    pause',
    '    exit /b 1',
    ')',
    'echo [OK] Directories OK',
    'echo.',
    '',
    ':: Check Python',
    'python --version >nul 2>&1',
    'if errorlevel 1 (',
    '    echo [FAIL] Python not found in PATH',
    '    pause',
    '    exit /b 1',
    ')',
    'python -c "import sys; exit(0 if sys.version_info >= (3,9) else 1)" >nul 2>&1',
    'if errorlevel 1 (',
    '    echo [FAIL] Python 3.9+ required',
    '    pause',
    '    exit /b 1',
    ')',
    'for /f "tokens=2" %%v in (''python --version 2^>nul'') do echo [OK] Python %%v',
    '',
    ':: Check Node.js',
    'node --version >nul 2>&1',
    'if errorlevel 1 (',
    '    echo [FAIL] Node.js not found in PATH',
    '    pause',
    '    exit /b 1',
    ')',
    'node -e "const v=parseInt(process.version.slice(1));if(v<18){process.exit(1)}" >nul 2>&1',
    'if errorlevel 1 (',
    '    echo [FAIL] Node.js 18+ required',
    '    pause',
    '    exit /b 1',
    ')',
    'for /f "delims=" %%v in (''node --version'') do echo [OK] Node.js %%v',
    'echo.',
    '',
    ':: Check backend venv',
    'if not exist "%BACKEND_DIR%\venv" (',
    '    echo [WARN] venv not found, creating...',
    '    cd /d "%BACKEND_DIR%"',
    '    python -m venv venv',
    '    if errorlevel 1 (',
    '        echo [FAIL] venv creation failed',
    '        pause',
    '        exit /b 1',
    '    )',
    '    echo [OK] venv created',
    '    call venv\Scripts\activate.bat',
    '    pip install -r requirements.txt',
    '    call venv\Scripts\deactivate.bat',
    '    echo [OK] Backend deps installed',
    ') else (',
    '    echo [OK] Backend venv exists',
    ')',
    '',
    ':: Check frontend node_modules',
    'if not exist "%FRONTEND_DIR%\node_modules" (',
    '    echo [WARN] node_modules not found, installing...',
    '    cd /d "%FRONTEND_DIR%"',
    '    npm install',
    '    if errorlevel 1 (',
    '        echo [FAIL] npm install failed',
    '        pause',
    '        exit /b 1',
    '    )',
    '    echo [OK] Frontend deps installed',
    ') else (',
    '    echo [OK] Frontend node_modules exists',
    ')',
    'echo.',
    '',
    ':: Check port 8000',
    'netstat -ano | findstr ":8000" >nul 2>&1',
    'if not errorlevel 1 (',
    '    echo [WARN] Port 8000 in use, killing...',
    '    for /f "tokens=5" %%a in (''netstat -ano ^| findstr ":8000"'') do (',
    '        if not "%%a"=="0" taskkill /F /PID %%a >nul 2>&1',
    '    )',
    '    timeout /t 2 >nul',
    '    echo [OK] Port 8000 freed',
    ') else (',
    '    echo [OK] Port 8000 available',
    ')',
    '',
    ':: Check port 5173',
    'netstat -ano | findstr ":5173" >nul 2>&1',
    'if not errorlevel 1 (',
    '    echo [WARN] Port 5173 in use, Vite will pick another port',
    ') else (',
    '    echo [OK] Port 5173 available',
    ')',
    'echo.',
    '',
    ':: Start backend in new window',
    'echo [1/2] Starting backend...',
    'start "ZhiXueBan-Backend" /d "%BACKEND_DIR%" cmd /k "%~dp0helper-backend.bat"',
    'timeout /t 3 >nul',
    'echo [OK] Backend window opened',
    'echo.',
    '',
    ':: Start frontend in new window',
    'echo [2/2] Starting frontend...',
    'start "ZhiXueBan-Frontend" /d "%FRONTEND_DIR%" cmd /k "%~dp0helper-frontend.bat"',
    'timeout /t 2 >nul',
    'echo [OK] Frontend window opened',
    'echo.',
    '',
    'echo ========================================',
    'echo   Both services started',
    'echo ========================================',
    'echo.',
    'echo Backend : http://127.0.0.1:8000',
    'echo API Docs: http://127.0.0.1:8000/docs',
    'echo.',
    'echo Frontend will open in browser automatically.',
    'echo.',
    'echo Keep the two service windows open.',
    'echo Press any key to close this window (services keep running)...',
    'pause >nul'
)

$text = $lines -join "`r`n"
[System.IO.File]::WriteAllBytes('E:\AI_projects\Web\scripts\start\5-一键启动前后端.bat', $enc.GetBytes($text))
Write-Host '[OK] 5-one-click.bat written in GBK encoding'
